services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: e-market-api:latest
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: e-market-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: my-redis-server
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
    name: e-market-redis-data
  mongo_data:
    name: e-market-mongo-data